version: '3'
services:
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/srv/http/php-crawler
    depends_on:
      - mysql
      - redis
      - rabbitmq

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: php_crawler
      MYSQL_USER: php_crawler
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret

  redis:
    image: redis:4
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.7-management
